name: dev-deployment
on:
  pull_request:
    branches:
      - main

concurrency:
  group: dev-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Push docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::753392824297:role/github-actions-ecr-runner-role
          aws-region: us-east-1   

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.15.6

      - name: Set S3 backend
        run: |
          cat > terraform/backend.tf << 'EOF'
          terraform {
            backend "s3" {}
          }
          EOF

      - name: Terraform Init
        run: terraform -chdir=terraform init -backend-config=backend-configs/prod-backend.tfvars
      
      - name: Select Terraform workspace
        run: terraform -chdir=terraform workspace select dev || terraform -chdir=terraform workspace new dev

      - name: Terraform Plan
        run: |
          terraform -chdir=terraform plan \
            -no-color \
            -var="image_tag=${{ github.sha }}" \
            -target=module.ecs_stack.aws_ecs_task_definition.main \
            -target=module.ecs_stack.aws_ecs_service.main \
            -out=dev.tfplan

      - name: Terraform apply
        run: |
          terraform -chdir=terraform apply \
            -auto-approve \
            -no-color \
            -target=module.ecs_stack.aws_ecs_task_definition.main \
            -target=module.ecs_stack.aws_ecs_service.main \
            dev.tfplan
