name: main-deployment
on:
  push:
    branches:
      - main

concurrency:
  group: prod-deployment
  cancel-in-progress: false

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Push docker image
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::753392824297:role/prod-github-actions-ecr-runner-role
          aws-region: us-east-1   

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

    #   - name: Build, Tag, and Push Docker image to Amazon ECR
    #     env:
    #       ECR_REGISTRY: 753392824297.dkr.ecr.us-east-1.amazonaws.com
    #       ECR_REPOSITORY: prod-default-project-name
    #       IMAGE_TAG: ${{ github.sha }}
    #     run: | 
    #       docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG nginx-docker
    #       docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.15.6

      - name: Set S3 backend
        run: |
          cat > terraform/backend.tf << 'EOF'
          terraform {
            backend "s3" {}
          }
          EOF

      - name: Terraform Init
        run: terraform -chdir=terraform init -backend-config=backend-configs/prod-backend.tfvars
      
      - name: Select Terraform workspace
        run: terraform -chdir=terraform workspace select prod || terraform -chdir=terraform workspace new prod

      - name: Terraform Plan
        run: |
          terraform -chdir=terraform plan \
            -no-color \
            -var="image_tag=${{ github.sha }}" \
            -target='module.ecs_stack["nginx-docker"].aws_ecs_task_definition.main' \
            -target='module.ecs_stack["nginx-docker"].aws_ecs_service.main' \
            -target='module.ecs_stack["api-service"].aws_ecs_task_definition.main' \
            -target='module.ecs_stack["api-service"].aws_ecs_service.main' \
            -target='terraform_data.build_and_push_images["nginx-docker"]' \
            -target='terraform_data.build_and_push_images["api-service"]' \
            -out=prod.tfplan
      - name: Terraform apply
        run: |
          terraform -chdir=terraform apply \
            -auto-approve \
            -no-color \
            -target='module.ecs_stack["nginx-docker"].aws_ecs_task_definition.main' \
            -target='module.ecs_stack["nginx-docker"].aws_ecs_service.main' \
            -target='module.ecs_stack["api-service"].aws_ecs_task_definition.main' \
            -target='module.ecs_stack["api-service"].aws_ecs_service.main' \
            -target='terraform_data.build_and_push_images["nginx-docker"]' \
            -target='terraform_data.build_and_push_images["api-service"]' \
            prod.tfplan

      - name: Print ALB DNS name
        run: terraform -chdir=terraform output -raw alb_dns_name
